#!/bin/sh

PROJECT_PATH=$PWD/$(dirname `which $0`)

# clean data
rm $PROJECT_PATH/data/results.ttl
rm $PROJECT_PATH/data/results.uniq.ttl
rm $PROJECT_PATH/public/db.ttl.gz
rm /tmp/results.ttl
rm /tmp/mesh_ontology.ttl

node $PROJECT_PATH/lib/utils/update_data.js


(cd $PROJECT_PATH
echo "clear db"
isql exec="SPARQL CLEAR GRAPH <http://kalitmo.org/itcancer>;"
sleep 5
cp data/mesh_ontology.ttl /tmp/mesh_ontology.ttl
echo "insert mesh_ontology.ttl"
isql exec="DB.DBA.TTLP (file_to_string_output ('/tmp/mesh_ontology.ttl'), '', 'http://kalitmo.org/itcancer', 64);"
sleep 5
echo "remove duplicated lines"
sort -u data/results.ttl > data/results.uniq.ttl
cp data/results.uniq.ttl /tmp/results.ttl
sleep 5
echo "insert results.ttl"
isql exec="DB.DBA.TTLP (file_to_string_output ('/tmp/results.ttl'), '', 'http://kalitmo.org/itcancer', 64);"
echo "zip db in /public"
gzip -f /tmp/results.ttl
mv /tmp/results.ttl.gz public/db.ttl.gz
)

